### ISSUE TITLE
Optimize Data Loading for Products Page

### ISSUE THREAD

**Issue by ddave7** [hamitsehjal/CampusCart-MAIN#43]
**User Story: Optimize Data Loading for Products Page**

**Description:**
As a user, I want the Products Page to load quickly and efficiently to access product information without delays.

**Acceptance Criteria:**

1. **Efficient Data Retrieval:**
   - [x] When I navigate to the Products Page, product data is retrieved from the backend API efficiently.

2. **Loading Indicator:**
   - [x] A loading indicator or spinner is displayed while product data is being fetched, providing feedback to the user.

**Comment by hamitsehjal** [comment]
[Request Merged](https://github.com/hamitsehjal/CampusCart-FRONTEND/pull/31)

Implemented the logic for the Products page loading products quickly and efficiently to access product information without delays.

- Efficient Data Retrieval
- Implement Client-Side Filtering for Products
- Category Selection
- Real-Time Filtering
- Clear Filters
