### ISSUE TITLE
Implement Client-Side Filtering for Products

### ISSUE THREAD

**Issue by ddave7** [hamitsehjal/CampusCart-MAIN#44]
**User Story: Implement Client-Side Filtering for Products**

**Description:**
As a user, I want to be able to filter products on the Products Page based on categories using an intuitive and visual interface.

**Acceptance Criteria:**

1. **Category Selection:**
   - [x] On the Products Page, I can select product categories from a list of options.

2. **Real-Time Filtering:**
   - [x] As I select a category, the list of displayed products is instantly updated to include only products from the selected category.

3. **Clear Filters:**
   - [x] I have the option to clear category filters to view all available products again.

4. **Responsive Design:**
   - [x] The filtering interface is designed to work seamlessly on various devices, ensuring a consistent user experience.

**Comment by hamitsehjal** [comment]
[Request Merged](https://github.com/hamitsehjal/CampusCart-FRONTEND/pull/31)

Implemented the logic for the Products page loading products quickly and efficiently to access product information without delays.

- Efficient Data Retrieval
- Implement Client-Side Filtering for Products
- Category Selection
- Real-Time Filtering
- Clear Filters
